### ISSUE TITLE
将os_admin改成Tp5版本，是一个简单的后台

### ISSUE THREAD

**Issue by seikai10** [kebenxiaoming/s_admin#1]
php环境和th5都已安装ok。我第一次接触th5，请问修改如何才能登录。

**Comment by kebenxiaoming** [comment]
需要自己安装验证码的composer包，然后你说的具体什么问题啊

**Comment by seikai10** [comment]
composer包没安装

**Comment by kebenxiaoming** [comment]
@seikai10 那你先安装啊，不然验证码刷不出来，在项目根目录执行:composer require topthink/think-captcha

**Comment by kebenxiaoming** [comment]
注意

```
if(!captcha_check($captcha)){
 //验证失败
};
```

也就是login.php中验证码验证地改改,去掉!
@seikai10

**Comment by kebenxiaoming** [comment]
用最新版吧，问题我管关了，最新版直接可用
